# Generated by Django 5.1 on 2024-09-09 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0010_blog_blogsingle_comment_opinion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='priz',
            name='n',
        ),
    ]
