# Generated by Django 5.1 on 2024-09-09 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0011_remove_priz_n'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='upload_at',
            field=models.CharField(blank=True, max_length=111, null=True),
        ),
    ]
